version: '3.8'

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sa123
      - POSTGRES_DB=bezkoder_db
    ports:
      - 5433:5432
    volumes:
      - db:/var/lib/postgres
  app:
    depends_on:
      - postgresdb
    build: ./bezkoder-app
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 6868:8080
    environment:
      - DB_HOST=postgresdb
      - DB_USER=postgres
      - DB_PASSWORD=sa123
      - DB_NAME=bezkoder_db
      - DB_PORT=5432
    stdin_open: true
    tty: true

volumes: 
  db:
